# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'RealDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealDemo
#  pod 'SDWebImage', '~> 5.0'
  # 本地路径依赖
#  pod 'RealSDK', :path => '../RealSDK'

end
